---
# tasks file for training

- name: ensure {{package_name}} is {{package_state}}
  yum:
    name: "{{package_name}}"
    state: "{{package_state}}"
  become: true
  when: package_name == "git"
  tags:
    - install_package


- name: ensure user toto is present
  user:
    name: "{{item}}"
  become: true
  with_items: "{{user_list}}"
  tags:
    - create_user


- name: ensure user is absent
  user:
    name: "{{item}}"
    state: absent
    remove: true
  with_items: "{{user_list}}"
  become: true
  tags:
    - delete_user

- name: deploy
  template:
    src: 'toto.txt.j2'
    dest: '/home/ip/github/begin/toto.txt'
  tags:
    - deploy
